<?php

namespace ContainerVLzDf2o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FoyV6xLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.foyV6xL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.foyV6xL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'character' => ['privates', '.errored..service_locator.foyV6xL.App\\Entity\\Character', NULL, 'Cannot autowire service ".service_locator.foyV6xL": it references class "App\\Entity\\Character" but no such service exists.'],
            'characterRepository' => ['privates', 'App\\Repository\\CharacterRepository', 'getCharacterRepositoryService', true],
        ], [
            'character' => 'App\\Entity\\Character',
            'characterRepository' => 'App\\Repository\\CharacterRepository',
        ]);
    }
}
