<?php

namespace ContainerVLzDf2o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5MIH3kPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5MIH3kP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5MIH3kP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'game' => ['privates', '.errored..service_locator.5MIH3kP.App\\Entity\\Game', NULL, 'Cannot autowire service ".service_locator.5MIH3kP": it references class "App\\Entity\\Game" but no such service exists.'],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'validator' => ['services', '.container.private.validator', 'get_Container_Private_ValidatorService', false],
        ], [
            'entityManager' => '?',
            'game' => 'App\\Entity\\Game',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
