<?php

namespace ContainerVLzDf2o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGallery2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FAoqVuo.App\Entity\Gallery' shared service.
     *
     * @return \App\Entity\Gallery
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.FAoqVuo": it references class "App\\Entity\\Gallery" but no such service exists.');
    }
}
