<?php

namespace ContainerVLzDf2o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.G48BACS.App\Entity\Mode' shared service.
     *
     * @return \App\Entity\Mode
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.G48BACS": it references class "App\\Entity\\Mode" but no such service exists.');
    }
}
