<?php

namespace ContainerDXXaIiP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BsspqSRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BsspqSR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BsspqSR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'game' => ['privates', '.errored..service_locator.BsspqSR.App\\Entity\\Game', NULL, 'Cannot autowire service ".service_locator.BsspqSR": it references class "App\\Entity\\Game" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.BsspqSR.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.BsspqSR": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'game' => 'App\\Entity\\Game',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
