<?php

namespace ContainerDXXaIiP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G48BACSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G48BACS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G48BACS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mode' => ['privates', '.errored..service_locator.G48BACS.App\\Entity\\Mode', NULL, 'Cannot autowire service ".service_locator.G48BACS": it references class "App\\Entity\\Mode" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'mode' => 'App\\Entity\\Mode',
        ]);
    }
}
