<?php

namespace ContainerDXXaIiP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGame4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bsUIPaZ.App\Entity\Game' shared service.
     *
     * @return \App\Entity\Game
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.bsUIPaZ": it references class "App\\Entity\\Game" but no such service exists.');
    }
}
