<?php

namespace ContainerDXXaIiP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOdiceyCreateUserCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\OdiceyCreateUserCommand' shared autowired service.
     *
     * @return \App\Command\OdiceyCreateUserCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/OdiceyCreateUserCommand.php';

        $container->privates['App\\Command\\OdiceyCreateUserCommand'] = $instance = new \App\Command\OdiceyCreateUserCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setName('odicey:create-user');
        $instance->setDescription('Create a new user for O\'Dicey');

        return $instance;
    }
}
