<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Game extends \App\Entity\Game implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'mode', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'dm', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'characters', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'galleries', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'gameUsers'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'mode', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'dm', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'characters', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'galleries', '' . "\0" . 'App\\Entity\\Game' . "\0" . 'gameUsers'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Game $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Game
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(int $status): \App\Entity\Game
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): \App\Entity\Game
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeImmutable $createdAt): \App\Entity\Game
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getMode(): ?\App\Entity\Mode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMode', []);

        return parent::getMode();
    }

    /**
     * {@inheritDoc}
     */
    public function setMode(?\App\Entity\Mode $mode): \App\Entity\Game
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMode', [$mode]);

        return parent::setMode($mode);
    }

    /**
     * {@inheritDoc}
     */
    public function getDm(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDm', []);

        return parent::getDm();
    }

    /**
     * {@inheritDoc}
     */
    public function setDm(?\App\Entity\User $dm): \App\Entity\Game
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDm', [$dm]);

        return parent::setDm($dm);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacters(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacters', []);

        return parent::getCharacters();
    }

    /**
     * {@inheritDoc}
     */
    public function addCharacter(\App\Entity\Character $character): \App\Entity\Game
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCharacter', [$character]);

        return parent::addCharacter($character);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCharacter(\App\Entity\Character $character): \App\Entity\Game
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCharacter', [$character]);

        return parent::removeCharacter($character);
    }

    /**
     * {@inheritDoc}
     */
    public function getGalleries(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGalleries', []);

        return parent::getGalleries();
    }

    /**
     * {@inheritDoc}
     */
    public function addGalleries(\App\Entity\Gallery $gallery): \App\Entity\Game
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGalleries', [$gallery]);

        return parent::addGalleries($gallery);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGalleries(\App\Entity\Gallery $gallery): \App\Entity\Game
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGalleries', [$gallery]);

        return parent::removeGalleries($gallery);
    }

    /**
     * {@inheritDoc}
     */
    public function getGameUsers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGameUsers', []);

        return parent::getGameUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addGameUser(\App\Entity\GameUsers $gameUser): \App\Entity\Game
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGameUser', [$gameUser]);

        return parent::addGameUser($gameUser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGameUser(\App\Entity\GameUsers $gameUser): \App\Entity\Game
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGameUser', [$gameUser]);

        return parent::removeGameUser($gameUser);
    }

}
