<?php

namespace ContainerH3qzmyo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_21oQotzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.21oQotz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.21oQotz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'game' => ['privates', '.errored..service_locator.21oQotz.App\\Entity\\Game', NULL, 'Cannot autowire service ".service_locator.21oQotz": it references class "App\\Entity\\Game" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'game' => 'App\\Entity\\Game',
        ]);
    }
}
