<?php

namespace ContainerH3qzmyo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FAoqVuoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FAoqVuo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FAoqVuo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'gallery' => ['privates', '.errored..service_locator.FAoqVuo.App\\Entity\\Gallery', NULL, 'Cannot autowire service ".service_locator.FAoqVuo": it references class "App\\Entity\\Gallery" but no such service exists.'],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'validator' => ['services', '.container.private.validator', 'get_Container_Private_ValidatorService', false],
        ], [
            'entityManager' => '?',
            'gallery' => 'App\\Entity\\Gallery',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
