<?php

namespace ContainerH3qzmyo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOdiceyDeactivateGamesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\OdiceyDeactivateGamesCommand' shared autowired service.
     *
     * @return \App\Command\OdiceyDeactivateGamesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/OdiceyDeactivateGamesCommand.php';

        $container->privates['App\\Command\\OdiceyDeactivateGamesCommand'] = $instance = new \App\Command\OdiceyDeactivateGamesCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setName('odicey:deactivate-games');
        $instance->setDescription('Deactive games with updates older than 1 year');

        return $instance;
    }
}
