<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVLzDf2o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVLzDf2o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVLzDf2o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVLzDf2o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVLzDf2o\App_KernelDevDebugContainer([
    'container.build_hash' => 'VLzDf2o',
    'container.build_id' => '1bcd1d47',
    'container.build_time' => 1690981050,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVLzDf2o');
