<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDXXaIiP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDXXaIiP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDXXaIiP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDXXaIiP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDXXaIiP\App_KernelDevDebugContainer([
    'container.build_hash' => 'DXXaIiP',
    'container.build_id' => '19af57ff',
    'container.build_time' => 1685027265,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDXXaIiP');
