<?php

namespace ContainerBtQVSCm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LrDVvpwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lrDVvpw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lrDVvpw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'modeRepository' => ['privates', 'App\\Repository\\ModeRepository', 'getModeRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'modeRepository' => 'App\\Repository\\ModeRepository',
            'paginator' => '?',
        ]);
    }
}
