<?php

namespace ContainerBtQVSCm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X0_H6lkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X0.H6lk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X0.H6lk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mode' => ['privates', '.errored..service_locator.X0.H6lk.App\\Entity\\Mode', NULL, 'Cannot autowire service ".service_locator.X0.H6lk": it references class "App\\Entity\\Mode" but no such service exists.'],
            'modeRepository' => ['privates', 'App\\Repository\\ModeRepository', 'getModeRepositoryService', true],
        ], [
            'mode' => 'App\\Entity\\Mode',
            'modeRepository' => 'App\\Repository\\ModeRepository',
        ]);
    }
}
